# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EEGLAB.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EEGLAB(object):
    def setupUi(self, EEGLAB):
        EEGLAB.setObjectName("EEGLAB")
        EEGLAB.resize(781, 596)
        self.centralwidget = QtWidgets.QWidget(EEGLAB)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QmyFigureCanvas(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stream_left = QtWidgets.QPushButton(self.groupBox)
        self.stream_left.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/610.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stream_left.setIcon(icon)
        self.stream_left.setObjectName("stream_left")
        self.horizontalLayout.addWidget(self.stream_left)
        self.stop = QtWidgets.QPushButton(self.groupBox)
        self.stop.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/624.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon1)
        self.stop.setObjectName("stop")
        self.horizontalLayout.addWidget(self.stop)
        self.stream_continue = QtWidgets.QPushButton(self.groupBox)
        self.stream_continue.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/620.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stream_continue.setIcon(icon2)
        self.stream_continue.setObjectName("stream_continue")
        self.horizontalLayout.addWidget(self.stream_continue)
        self.stream_right = QtWidgets.QPushButton(self.groupBox)
        self.stream_right.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/612.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stream_right.setIcon(icon3)
        self.stream_right.setObjectName("stream_right")
        self.horizontalLayout.addWidget(self.stream_right)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout.setStretch(0, 9)
        self.verticalLayout.setStretch(1, 1)
        EEGLAB.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EEGLAB)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 781, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSignals = QtWidgets.QMenu(self.menubar)
        self.menuSignals.setObjectName("menuSignals")
        self.menuFilter = QtWidgets.QMenu(self.menubar)
        self.menuFilter.setObjectName("menuFilter")
        self.menuTimesync = QtWidgets.QMenu(self.menubar)
        self.menuTimesync.setObjectName("menuTimesync")
        self.menuAnnotation = QtWidgets.QMenu(self.menubar)
        self.menuAnnotation.setObjectName("menuAnnotation")
        self.menushow = QtWidgets.QMenu(self.menubar)
        self.menushow.setObjectName("menushow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        EEGLAB.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EEGLAB)
        self.statusbar.setObjectName("statusbar")
        EEGLAB.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(EEGLAB)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_stream = QtWidgets.QAction(EEGLAB)
        self.actionOpen_stream.setObjectName("actionOpen_stream")
        self.actionStart_Video = QtWidgets.QAction(EEGLAB)
        self.actionStart_Video.setObjectName("actionStart_Video")
        self.actionSave_as = QtWidgets.QAction(EEGLAB)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtWidgets.QAction(EEGLAB)
        self.actionExit.setObjectName("actionExit")
        self.actionProperties = QtWidgets.QAction(EEGLAB)
        self.actionProperties.setObjectName("actionProperties")
        self.actionAdd = QtWidgets.QAction(EEGLAB)
        self.actionAdd.setObjectName("actionAdd")
        self.actionNew = QtWidgets.QAction(EEGLAB)
        self.actionNew.setObjectName("actionNew")
        self.actionAdjust = QtWidgets.QAction(EEGLAB)
        self.actionAdjust.setObjectName("actionAdjust")
        self.actionRemove_all = QtWidgets.QAction(EEGLAB)
        self.actionRemove_all.setObjectName("actionRemove_all")
        self.actionGo_to_start_of_file = QtWidgets.QAction(EEGLAB)
        self.actionGo_to_start_of_file.setObjectName("actionGo_to_start_of_file")
        self.actionGo_to_end_of_file = QtWidgets.QAction(EEGLAB)
        self.actionGo_to_end_of_file.setObjectName("actionGo_to_end_of_file")
        self.actionJump_to = QtWidgets.QAction(EEGLAB)
        self.actionJump_to.setObjectName("actionJump_to")
        self.actionAnnotations = QtWidgets.QAction(EEGLAB)
        self.actionAnnotations.setObjectName("actionAnnotations")
        self.actionAnnotation_editor = QtWidgets.QAction(EEGLAB)
        self.actionAnnotation_editor.setObjectName("actionAnnotation_editor")
        self.actionPower_Spectrum = QtWidgets.QAction(EEGLAB)
        self.actionPower_Spectrum.setObjectName("actionPower_Spectrum")
        self.actionPhase = QtWidgets.QAction(EEGLAB)
        self.actionPhase.setObjectName("actionPhase")
        self.actionAbout_EEGLAB = QtWidgets.QAction(EEGLAB)
        self.actionAbout_EEGLAB.setObjectName("actionAbout_EEGLAB")
        self.actionVideos = QtWidgets.QAction(EEGLAB)
        self.actionVideos.setObjectName("actionVideos")
        self.actionTutor = QtWidgets.QAction(EEGLAB)
        self.actionTutor.setObjectName("actionTutor")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_stream)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionStart_Video)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSignals.addAction(self.actionProperties)
        self.menuSignals.addAction(self.actionAdd)
        self.menuFilter.addAction(self.actionNew)
        self.menuFilter.addAction(self.actionAdjust)
        self.menuFilter.addAction(self.actionRemove_all)
        self.menuTimesync.addAction(self.actionGo_to_start_of_file)
        self.menuTimesync.addAction(self.actionGo_to_end_of_file)
        self.menuTimesync.addAction(self.actionJump_to)
        self.menuAnnotation.addAction(self.actionAnnotations)
        self.menuAnnotation.addAction(self.actionAnnotation_editor)
        self.menushow.addSeparator()
        self.menushow.addAction(self.actionPower_Spectrum)
        self.menushow.addAction(self.actionPhase)
        self.menuHelp.addAction(self.actionAbout_EEGLAB)
        self.menuHelp.addAction(self.actionVideos)
        self.menuHelp.addAction(self.actionTutor)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnnotation.menuAction())
        self.menubar.addAction(self.menushow.menuAction())
        self.menubar.addAction(self.menuSignals.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())
        self.menubar.addAction(self.menuTimesync.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(EEGLAB)
        self.actionExit.triggered.connect(EEGLAB.close)
        QtCore.QMetaObject.connectSlotsByName(EEGLAB)

    def retranslateUi(self, EEGLAB):
        _translate = QtCore.QCoreApplication.translate
        EEGLAB.setWindowTitle(_translate("EEGLAB", "MainWindow"))
        self.menuFile.setTitle(_translate("EEGLAB", "File"))
        self.menuSignals.setTitle(_translate("EEGLAB", "Signals"))
        self.menuFilter.setTitle(_translate("EEGLAB", "Filter"))
        self.menuTimesync.setTitle(_translate("EEGLAB", "Timesync"))
        self.menuAnnotation.setTitle(_translate("EEGLAB", "Annotation"))
        self.menushow.setTitle(_translate("EEGLAB", "show"))
        self.menuHelp.setTitle(_translate("EEGLAB", "Help"))
        self.actionOpen.setText(_translate("EEGLAB", "Open"))
        self.actionOpen_stream.setText(_translate("EEGLAB", "Open stream"))
        self.actionStart_Video.setText(_translate("EEGLAB", "Start Video"))
        self.actionSave_as.setText(_translate("EEGLAB", "Save as"))
        self.actionSave_as.setShortcut(_translate("EEGLAB", "Ctrl+S"))
        self.actionExit.setText(_translate("EEGLAB", "Exit"))
        self.actionProperties.setText(_translate("EEGLAB", "Properties"))
        self.actionAdd.setText(_translate("EEGLAB", "Add"))
        self.actionNew.setText(_translate("EEGLAB", "New"))
        self.actionAdjust.setText(_translate("EEGLAB", "Adjust"))
        self.actionRemove_all.setText(_translate("EEGLAB", "Remove all"))
        self.actionGo_to_start_of_file.setText(_translate("EEGLAB", "Go to start of file"))
        self.actionGo_to_end_of_file.setText(_translate("EEGLAB", "Go to end of file"))
        self.actionJump_to.setText(_translate("EEGLAB", "Jump to"))
        self.actionAnnotations.setText(_translate("EEGLAB", "Annotations"))
        self.actionAnnotation_editor.setText(_translate("EEGLAB", "Annotation editor"))
        self.actionPower_Spectrum.setText(_translate("EEGLAB", "Power Spectrum"))
        self.actionPhase.setText(_translate("EEGLAB", "Phase"))
        self.actionAbout_EEGLAB.setText(_translate("EEGLAB", "About EEGLAB"))
        self.actionVideos.setText(_translate("EEGLAB", "Videos "))
        self.actionTutor.setText(_translate("EEGLAB", "Tutor"))

from myFigureCanvas import QmyFigureCanvas
import res_rc
