# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 443)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 532, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuImport_data = QtWidgets.QMenu(self.menuFile)
        self.menuImport_data.setObjectName("menuImport_data")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        self.menuPlot = QtWidgets.QMenu(self.menuBar)
        self.menuPlot.setObjectName("menuPlot")
        self.menuDatasets = QtWidgets.QMenu(self.menuBar)
        self.menuDatasets.setObjectName("menuDatasets")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actFile_Import_epoch_info = QtWidgets.QAction(MainWindow)
        self.actFile_Import_epoch_info.setObjectName("actFile_Import_epoch_info")
        self.actFile_Import_event_info = QtWidgets.QAction(MainWindow)
        self.actFile_Import_event_info.setObjectName("actFile_Import_event_info")
        self.actFile_Open = QtWidgets.QAction(MainWindow)
        self.actFile_Open.setObjectName("actFile_Open")
        self.actFile_Save = QtWidgets.QAction(MainWindow)
        self.actFile_Save.setObjectName("actFile_Save")
        self.actFile_Save_As = QtWidgets.QAction(MainWindow)
        self.actFile_Save_As.setObjectName("actFile_Save_As")
        self.actFile_Quit = QtWidgets.QAction(MainWindow)
        self.actFile_Quit.setObjectName("actFile_Quit")
        self.actFile_Export = QtWidgets.QAction(MainWindow)
        self.actFile_Export.setObjectName("actFile_Export")
        self.actEdit_Select_Data = QtWidgets.QAction(MainWindow)
        self.actEdit_Select_Data.setObjectName("actEdit_Select_Data")
        self.actEdit_Select_epochs_events = QtWidgets.QAction(MainWindow)
        self.actEdit_Select_epochs_events.setObjectName("actEdit_Select_epochs_events")
        self.actTools_Change_Rate = QtWidgets.QAction(MainWindow)
        self.actTools_Change_Rate.setObjectName("actTools_Change_Rate")
        self.actTools_Filter_the_data = QtWidgets.QAction(MainWindow)
        self.actTools_Filter_the_data.setObjectName("actTools_Filter_the_data")
        self.actTools_Run_ICA = QtWidgets.QAction(MainWindow)
        self.actTools_Run_ICA.setObjectName("actTools_Run_ICA")
        self.actPlot_Data_statistics = QtWidgets.QAction(MainWindow)
        self.actPlot_Data_statistics.setObjectName("actPlot_Data_statistics")
        self.actPlot_Time_F_transforms = QtWidgets.QAction(MainWindow)
        self.actPlot_Time_F_transforms.setObjectName("actPlot_Time_F_transforms")
        self.actHelp_About_ComplexityLAB = QtWidgets.QAction(MainWindow)
        self.actHelp_About_ComplexityLAB.setObjectName("actHelp_About_ComplexityLAB")
        self.actHelp_Contact_us = QtWidgets.QAction(MainWindow)
        self.actHelp_Contact_us.setObjectName("actHelp_Contact_us")
        self.actEuro_EDF_file = QtWidgets.QAction(MainWindow)
        self.actEuro_EDF_file.setObjectName("actEuro_EDF_file")
        self.menuImport_data.addAction(self.actEuro_EDF_file)
        self.menuFile.addAction(self.menuImport_data.menuAction())
        self.menuFile.addAction(self.actFile_Import_epoch_info)
        self.menuFile.addAction(self.actFile_Import_event_info)
        self.menuFile.addAction(self.actFile_Export)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actFile_Open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actFile_Save)
        self.menuFile.addAction(self.actFile_Save_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actFile_Quit)
        self.menuEdit.addAction(self.actEdit_Select_Data)
        self.menuEdit.addAction(self.actEdit_Select_epochs_events)
        self.menuTools.addAction(self.actTools_Change_Rate)
        self.menuTools.addAction(self.actTools_Filter_the_data)
        self.menuTools.addAction(self.actTools_Run_ICA)
        self.menuPlot.addAction(self.actPlot_Data_statistics)
        self.menuPlot.addAction(self.actPlot_Time_F_transforms)
        self.menuHelp.addAction(self.actHelp_About_ComplexityLAB)
        self.menuHelp.addAction(self.actHelp_Contact_us)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuPlot.menuAction())
        self.menuBar.addAction(self.menuDatasets.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actFile_Quit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ComplexityLAB"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuImport_data.setTitle(_translate("MainWindow", "Import data"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuPlot.setTitle(_translate("MainWindow", "Plot"))
        self.menuDatasets.setTitle(_translate("MainWindow", "Datasets"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actFile_Import_epoch_info.setText(_translate("MainWindow", "Import epoch info"))
        self.actFile_Import_event_info.setText(_translate("MainWindow", "Import event info"))
        self.actFile_Open.setText(_translate("MainWindow", "Open"))
        self.actFile_Open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actFile_Save.setText(_translate("MainWindow", "Save"))
        self.actFile_Save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actFile_Save_As.setText(_translate("MainWindow", "Save As"))
        self.actFile_Save_As.setToolTip(_translate("MainWindow", "Save As..."))
        self.actFile_Quit.setText(_translate("MainWindow", "Quit"))
        self.actFile_Export.setText(_translate("MainWindow", "Export"))
        self.actEdit_Select_Data.setText(_translate("MainWindow", "Select Data"))
        self.actEdit_Select_epochs_events.setText(_translate("MainWindow", "Select epochs/events"))
        self.actTools_Change_Rate.setText(_translate("MainWindow", "Changing sampling rate"))
        self.actTools_Filter_the_data.setText(_translate("MainWindow", "Filter the data"))
        self.actTools_Run_ICA.setText(_translate("MainWindow", "Run ICA"))
        self.actPlot_Data_statistics.setText(_translate("MainWindow", "Data statistics"))
        self.actPlot_Time_F_transforms.setText(_translate("MainWindow", "Time-frequency transforms"))
        self.actHelp_About_ComplexityLAB.setText(_translate("MainWindow", "About ComplexityLAB"))
        self.actHelp_Contact_us.setText(_translate("MainWindow", "Contact us"))
        self.actEuro_EDF_file.setText(_translate("MainWindow", "From European Data Format.EDF file"))

